DROP TABLE IF EXISTS BATCH;
DROP TABLE IF EXISTS PLANT;
DROP TABLE IF EXISTS LOCATION_BATCH;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS PROJECT_LOCATION;
DROP TABLE IF EXISTS CLIENT_LOCATION;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS CLIENT_PROJECT;
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS LOGIN;
DROP TABLE IF EXISTS ROLES;


/* used in conjunction with LOGIN class to determine access level */
CREATE TABLE ROLES (
	ID INTEGER PRIMARY KEY,
	ROLENAME TEXT
);

INSERT INTO ROLES (ID,ROLENAME) VALUES (
	1,
	'Admin'
);

INSERT INTO ROLES (ID,ROLENAME) VALUES (
	2,
	'Employee'
);

INSERT INTO ROLES (ID,ROLENAME) VALUES (
	3,
	'Client'
);


/* holds the username/salted password as well as role */
CREATE TABLE LOGIN (
	ID SERIAL PRIMARY KEY,
	USERNAME TEXT,
	PASSWORD TEXT,
	ROLE INT FOREIGN KEY
);

/* Holds information pertaining to how the particular login is related to the cleint */
CREATE TABLE CLIENT_LOGIN (
	ID SERIAL PRIMARY KEY,
	CLIENT_ID INT FOREIGN KEY,
	LOGIN_ID INT FOREIGN KEY
);


/* Holds information about a batch */

CREATE TABLE BATCH (
	ID SERIAL PRIMARY KEY,
	RFID TEXT,
	CREATION_DATE DATE,
	PLANT_ID INT FOREIGN KEY,
	FAILURE BOOLEAN
);

/* Holds information about a plant */
CREATE TABLE PLANT(
	ID SERIAL PRIMARY KEY,
	PLANT_NAME TEXT
);

/* Connects a batch to a certain location */
CREATE TABLE LOCATION_BATCH (
	ID SERIAL PRIMARY KEY,
	ARRIVAL_DATE DATE,
	BATCH_ID INT FOREIGN KEY,
	LOCATION_ID INT FOREIGN KEY
);

/* Information about where ACME pours their concrete */
CREATE TABLE LOCATION (
	ID SERIAL PRIMARY KEY,
	LOCATION_NAME TEXT
);

/* Information about how the project relates to a particular location */
CREATE TABLE PROJECT_LOCATION (
	ID SERIAL PRIMARY KEY,
	PROJECT_ID INT FOREIGN KEY,
	LOCATION_ID INT FOREIGN KEY
);

/* Information about how a client relates to a location */
CREATE TABLE CLIENT_LOCATION (
	ID SERIAL PRIMARY KEY,
	LOCATION_ID INT FOREIGN KEY,
	CLIENT_ID INT FOREIGN KEY
);

/* Information about how a client*/
CREATE TABLE CLIENT(
	ID SERIAL PRIMARY KEY,
	CLIENT_NAME TEXT,
	CLIENT_PHONE TEXT,
	CLIENT_EMAIL TEXT
);

/* Information about how a client relates to a project */
CREATE TABLE CLIENT_PROJECT (
	ID SERIAL PRIMARY KEY,
	CLIENT_ID INT FOREIGN KEY,
	PROJECT_ID INT FOREIGN KEY
);

/* Information about a specific project*/
CREATE TABLE PROJECT (
	ID SERIAL PRIMARY KEY,
	PROJECT_NAME TEXT
);
